---
- hosts: esxi
  gather_facts: false
  connection: local
  user: remote
  sudo: true

  vars_prompt:
    - name: "VC_hostname"
      prompt: "Enter vcenter hostname"
      private: no
      default: "vcsa"
    - name: "vcenter_user"
      prompt: "Enter vcenter username"
      private: no
    - name: "vcenter_pass"
      prompt: "Enter vcenter password"
      private: yes

  vars:
    esxi_host: '172.16.31.20'
    notes: 'Created by Ansible'
    inventory_hostname: 'test1'
    disk: 200
    datastore: 'ds2'
    network: 'cloud'
    memory: 2048
    cpucount: 1
    osid: otherLinux64Guest    

  tasks:
    - vsphere_guest:
        vcenter_hostname: "{{ VC_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        guest: "{{ inventory_hostname }}"
        state: present
        vm_extra_config:
          notes: "{{ notes }}"
        vm_disk:
          disk1:
            size_gb: "{{ disk }}"
            type: thin
            datastore: "{{ datastore }}"
        vm_nic:
          nic1:
            type: vmxnet3
            network: "{{ network }}"
            network_type: standard
        vm_hardware:
          memory_mb: "{{ memory }}"
          num_cpus: "{{ cpucount }}"
          osid: "{{ osid }}"
          scsi: paravirtual
        datacenter: Datacenter
        esxi:
          hostname: "{{ esxi_host }}"
